Annotator/config/routes.rb
TweetApp::Application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :annotations, only: [:create]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  root :to => 'static_pages#home'

  
  match '/instructions',    to: 'static_pages#help'
  match '/about',   to: "static_pages#about"
  match '/contact', to: "static_pages#contact"
  match '/why_not_chrome', to: "static_pages#why_not_chrome"

   

end

Annotator/app/models/annotation.rb
class Annotation < ActiveRecord::Base
  attr_accessible :email, :tweetId, :value
  belongs_to :user
  belongs_to :tweet 

end

Annotator/app/models/tweet.rb
class Tweet < ActiveRecord::Base
  attr_accessible :content, :replies, :tweetId

  has_many :annotations

  def self.find(*args)
    if args.first.to_s == "random"
      ids = connection.select_all("SELECT id FROM tweets")
      super(ids[rand(ids.length)]["id"].to_i)
    else
      super
    end
  end
end

Annotator/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                    :integer          not null, primary key
#  email                 :string(255)
#  number_of_annotations :integer
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#  password_digest       :string(255)
#  remember_token        :string(255)
#

class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password
  has_many :annotations, dependent: :destroy

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :name, presence: true, length: { minimum: 3 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 40 }, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  def feed
    # Collect the next tweet to be annotated, in order of preference
     Tweet.find('random')
    #  thesetweets = Tweet.where("id > ?", 0)
    #  thesetweets[0]
   # thistweet = Tweet.where("id > ?", 0)
   # thistweetId = thistweet.tweetId
    #if (Annotation.where("tweetId=?",tweetId) == null)
    
  end

  def counter
    @userId = User.where(:email => self.email).pluck(:id)
    Annotation.where(:user_id => @userId).count()
  end

  def rater
    if counter < 15
      ["A dour serf","adourserf.jpeg"]
    elsif counter < 30
      ["A humourless yeoman", "ahumourlessyeoman.png"]
    elsif counter < 50
      ["A mildly amusing jester", "amildlyamusingjester.png"]
    elsif counter < 70
      ["A cheerful merchant", "acheerfulmerchant.png"]
    elsif counter < 100
      ["A witty knight", "awittyknight.png"]
    elsif counter < 135
      ["A banterous baron", "abanterousbaron.png"]
    elsif counter < 170
      ["A sarcastic prince", "asarcasticprince.png"]
    else
      ["An ironic emperor", "anironicemperor.png"]
    end
  end


  

   private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

Annotator/app/controllers/annotations_controller.rb
class AnnotationsController < ApplicationController
    before_filter :signed_in_user

    def create
        @annotation = current_user.annotations.build(params[:annotation])
        if @annotation.save
            #flash[:success] = "Annotated!!"
            redirect_to root_url
        else
            render 'static_pages/home'
        end
    end
end

Annotator/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper

  #Force signout to prevent CSRF attacks
  def handle_unverified_request
    sign_out
    super
  end
end

Annotator/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

Annotator/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
        user = User.find_by_email(params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
          sign_in user
          redirect_back_or user
        else
          flash.now[:error] = 'Invalid email/password combination'
          render 'new'
        end
    end

    def destroy
        sign_out
        redirect_to root_url
    end
end

Annotator/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    if signed_in?
      #@tweet = current_user.tweets.build
      @feed_item = current_user.feed
      @annotation = current_user.annotations.build
      @count = current_user.counter
      @rating = current_user.rater
    end
  end

  def help
  end

  def about
  end

  def contact
  end

  def why_not_chrome
  end
end

Annotator/app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    before_filter :signed_in_user

    def create
      @tweet = current_user.tweets.build(params[:tweet])
      if @tweet.save
         flash[:success] = "tweet created!"
         redirect_to root_url
      else
        @feed_items = []
        render 'static_pages/home'
      end  
    end

    def destroy
    end
end

Annotator/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:edit, :update, :index, :destroy]
  before_filter :correct_user,   only: [:edit, :update, :show]
  before_filter :admin_user,     only: :destroy

  def show
    #if @user.username != params[:id]
      #redirect_to user_path(@user)
   # else
    @user = User.find(params[:id])
    @count = @user.counter
    @rating = @user.rater
    #@tweets = @user.tweets.paginate(page: params[:page])
 # end
  end

  def new
    @user = User.new 
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user 
      flash[:success] = "Welcome to the Annotator: Please remember that all questions are optional - you may logout of the application at any time."
      redirect_to @user
    else
      render 'new'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end

  def edit
  end
  
  def index
    @users = User.paginate(page: params[:page])
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

    def signed_in_user
      redirect_to signin_url, notice: "Please sign in." unless signed_in?
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
end

Annotator/app/helpers/annotations_helper.rb
module AnnotationsHelper
end

Annotator/app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Annotator"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

Annotator/app/helpers/home_helper.rb
module HomeHelper
end

Annotator/app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end
end

Annotator/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

Annotator/app/helpers/tweets_helper.rb
module TweetsHelper
end

Annotator/app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.email, class: "gravatar")
  end
end

Annotator/app/views/annotations/_annotation.html.erb
<li>
  <span class="content"><%= annotation.annotation_value %></span>
  <span class="timestamp">
    Annotated <%= time_ago_in_words(annotation.created_at) %> ago.
  </span>
</li>

Annotator/app/views/home/index.html.erb
<div class="center hero-unit">
  <h1>Welcome to the annotator</h1>

  <h2>
    This is the home page for the application.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>

<div align =center>
<%= link_to image_tag("me_speech.png", alt: "me") %>
</div>

Annotator/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Annotator
    by Sam
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

Annotator/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to image_tag("title.png", size: "250x35", alt: "The Annotator"), root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Instructions", instructions_path %></li>
          <li><%= link_to "Begin", root_path %></li>         
          <% if signed_in? %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

Annotator/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

Annotator/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      
    </div>
  </body>
</html>

Annotator/app/views/shared/_annotation_form.html.erb
<%= form_for(@annotation) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :annotation_value, placeholder: "Annotate the tweet..." %>
  </div>
  <%= f.submit "Submit", class: "btn btn-large btn-primary" %>
<% end %>

Annotator/app/views/shared/_answer_buttons.html.erb
<%= form_for(@annotation) do |f| %>

  <%= render 'shared/error_messages', object: f.object %>
    <div class="field">

     <br>

     <div class="btn-toolbar" data-toggle="buttons-radio">

       <button value="positive" name="annotation[value]" type="submit" class="btn btn-success" data-disable-with="submitting...">
         positive
       </button>

       <button value="sarcastic" name="annotation[value]" type="submit" class="btn btn-primary"data-disable-with="submitting...">  sarcastic
       </button>

      <button value="negative" name="annotation[value]" type="submit" class="btn btn-danger" data-disable-with="submitting...">
         negative
       </button>

       <button value="unclear" name="annotation[value]" type="submit" class="btn btn-warning" data-disable-with="submitting...">
         gibberish
       </button>

      <div id="divider" class="divider" /></div>
    <%= hidden_field(:annotation, :tweetId) %>
  </div>
<% end %>

Annotator/app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %> 

Annotator/app/views/shared/_feed.html.erb
  <ol class="tweets">
    <%= render partial: 'shared/feed_item' %>
  </ol>
 

Annotator/app/views/shared/_feed_item.html.erb
<li id="<%= @feed_item.content %>">
  <span class="user">
  </span>
  <span class="content"><%= @feed_item.content %></span>
  <span class="content"><% @annotation.tweetId = @feed_item.tweetId %></span>
  <hr>
  <span class="timestamp">
    <b>Replies:</b> 

    <br>
    <%= @feed_item.reply_1 %> 
    <br>
    <br>	
    <%= @feed_item.reply_2 %> 
    <br>
    <br>	
    <%= @feed_item.reply_3 %> 
    <br>
    <br>	
    <%= @feed_item.reply_4 %>
    <br> 
    <br>	
    <%= @feed_item.reply_5 %>
    <br> 
    <br>	
    <hr>
    <h4>Classification</h4> (Intended sentiment of the original tweet author): 
    <%= render partial: 'shared/answer_buttons' %> 
  </span>
</li>

Annotator/app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
<%= link_to image_tag(@rating[1]) %>
  </a>

<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<p>Tweets Annotated:
<%= @count %>
</p>
<p>Your rating: <%= @rating[0] %></p>
<br>
<br>




<span>
</span>

Annotator/app/views/static_pages/contact.html.erb
<%= link_to image_tag("contact-title.png", alt: "about page") %>
<br>
<br>
<p>
  If you have any questions, suggestions or feedback, please feel free to contact me at:
  albanies@tcd.ie
</p>

Annotator/app/views/static_pages/help.html.erb
<br>
<%= link_to image_tag("instructions-title.png", alt: "Instructions") %>
<br>
<br>
<h3>Background information</h3>
<br>
<br>
<br>
<br>
<p>
  This study is being conducted as part of research into techniques to improve <b class="sentimentgreen">sentiment analysis</b> on twitter data. 
  Essentially, this involves collecting a large number of tweets from twitter and building 
  a system that can be "trained" on some of these tweets to be able to decide whether or not 
  a tweet is positive or negative.  This is the sort of thing that can be useful to companies
  who want to know how the public is reacting to their product releases.
</p>
<br>
<p>
  For example, if people tweet: 
</p>
<br>
<p class="tweetcolor">
  "The new iphone is powerful, but I hate how heavy it is #applegravity #Newtonwouldlikeit"
</p>
<br>
<p>
  then by performing sentiment analysis, Apple can ascertain that there is a positive response to the iphone processor power, but a negative response to its weight.  This information (particularly when extracted from 
  hundreds of thousands of tweets) forms a valuable source of customer feedback.  It can be performed on a far larger scale than a survery and often offers a truer reflection of the users opinion.
</p>
<br>
<p>
    However, sarcasm makes this task very difficult.  It is comparatively simple to build a system that classifies the tweet from words that are associated with clearly positive or negative feelings (e.g 
    <em class="sentimentgreen">powerful</em> and <em class="sentimentred"> heavy</em> in the tweet above).  However, consider the following tweet:
</p>
<br>
<p class="tweetcolor">
  "I just love the new Samsung. It's incredible. So, so fast. #sarcasm"
</p>
<br>
<p> 
    A system that isn't trained to deal with sarcasm will see <em class="sentimentgreen">love</em>, <em class="sentimentgreen">incredible</em> and <em class="sentimentgreen">fast</em>, and classify the tweet as positive, which doesn't reflect the sentiment of the user at all!  In their raw form, tweets are a mass of unsorted snippets of information, mixed together without any structure.  The task of a classifer (the term given to such a system) is to separate this data into categories as accurately as possible.  To illustrate this concept, take a look at the diagram below and click 'Classify!' to see how the classifier aims to categorize the tweets:
</p>

  <div id="container" class="container">
    <div id="main" role="main">
      <div id="view_selection" class="btn-group">
        <a href="#" id="all" class="btn btn-primary active">Raw tweets</a>
        <a href="#" id="category" class="btn btn-success">Classify!</a>
      </div>
      <div id="vis"></div>
    </div>
  </div> <!--! end of #container -->

<br>
<p>
    As part of my research, I have designed a system that aims to achieve this separation by classifying tweets as positive, sarcastic or negative to deal with this problem of intended sentiment.  However, in order to test the effectiveness of the system, I need to compare it against humans.  The purpose of this study is establish a human benchmark for the difficulty of the task of deciding whether or not a tweet is sarcastic.
</p>
<br>
<h4>
  Course of study
</h4>
<br>
<p>
  This research is being conducted as part of the dissertation for an MSc. in Networks and Distributed Systems at Trinity College, Dublin.
</p>
<br>
<h4>
Declaration of conflicts of interest
</h4>
<br>
<p> 
Please note that your participation in this study is designed to allow me to make progress in my dissertation research.  Your contribution will be used under the criterion that you are a fluent English speaker. There are no external or corporate conflicts of interest relevant to this research.  
</p>
<br>
<h4>
This study is entirely voluntary
</h4>
<br>
<p>
As the participant, you may abandon the study at any point should you wish to do so.  You may omit responses to any questions that you do not wish to answer.  If for any reason at all you do not wish for your results to be used, please send me an email at albanies@tcd.ie and I will ensure that your answers will not be stored. 
<p/>
<br>
<h4>
Risks/benefits to the participant
</h4>
<br>
<p>
There is no financial compensation for particpation in this study.  Your results will be used entirely anonymously in any presentation or publication of results.  There are no direct health risks associated with participation in this study.  Once the research has been completed, you will have the option to obtain the results of your own performance by email request.  However, the results cannot be released while the study is still ongoing.
</p>
<br>
<h4>
Illicit activity
</h4>
<br>
<p>
Please note that in the extremely unlikely event that illicit activity is conducted I will be obliged to report it to appropriate authorities.
</p>
<br>
<h4>
Quotations and recordings
</h4>
<br>
<p>
No quotations, audio recordings or video recordings will be used from participants in the study.
</p>
<br>
<h3>Instructions</h3>
<br>
<p>
You will be presented with a series of tweets, one at a time, together with other replies or tweets that were part of that conversation (if there were any).  The task is simply to note whether you believe the intended meaning of the original tweet was positive sarcastic or negative.  The tweets themselves have been made anonymous as far as possible - the username of the tweeter has been removed and any tweets directed at a specific user have had the name of that user replaced with @SomeUser. 
</p>
<br>
<p>
 Some of the tweets my be badly formed or ambiguous.  In such cases, just give your best guess as to the intention of the original tweet author.  If they are completely unintelligble, there is an option to mark the tweet as 'gibberish'.  Please also note that some tweets may contain offensive language. 
</p>
<br>
<p>
 As a participator, no personal information of yours will be stored after the study or used in any form of publication. The information that you contribute as a participant will be used entirely anonymously.
</p>
<br>
<p>
There is no time limit in which to classify tweets.  There is no minimum or maximum number that you are required to classify.  However, as a guide, if you feel you are able to comfortably classify 200 tweets, this would be very useful for the purposes of the research.  In order to make the study more interesting, the more tweets that you classify, the more you will increase your 'level' as a participant, allowing you to unlock themed images.  This is purely to make the task more enjoyable.  The data relating to the levels of particpants will not recorded.
</p>
<br>
<p>
If you feel tired or uncomfortable, please take a break.  You may logout at any time and log back in at any time.  If you wish to abandon the study, you are completely free to do so at any time.  The results are recorded as tweets are classified, so to complete the task, simply log out of the application.
</p>
<br>

<%= link_to "Participate", signup_path, :class => "btn-large btn-success" %>
  
  <!-- end CSS-->

  <script src="js/libs/modernizr-2.0.6.min.js"></script>

    <script>window.jQuery || document.write('<script src="js/libs/jquery-1.6.2.min.js"><\/script>')</script>

  <script defer src="js/plugins.js"></script>
  <script defer src="js/script.js"></script>
  <script src="js/CustomTooltip.js"></script>
  <script src="js/libs/coffee-script.js"></script>
  <script src="js/libs/d3.min.js"></script>
  <script src="js/libs/d3.csv.min.js"></script>
  <script src="js/libs/d3.layout.min.js"></script>
  <script src="js/libs/d3.geom.min.js"></script>
  <script src="js/viz.js"></script>
  <script type="text/javascript">

   d3.csv("data/tweet_data2.csv", function(data) {
        custom_bubble_chart.init(data);
        custom_bubble_chart.toggle_view('all');
    });

    $(document).ready(function() {
        $(document).ready(function() {
          $('#view_selection a').click(function() {
            var view_type = $(this).attr('id');
            $('#view_selection a').removeClass('active');
            $(this).toggleClass('active');
            custom_bubble_chart.toggle_view(view_type);
            return false;
          });
        });
    });
  </script>


  <script>
    window._gaq = [['_setAccount','UA-17355070-1'],['_trackPageview'],['_trackPageLoadTime']];
    Modernizr.load({
      load: ('https:' == location.protocol ? '//ssl' : '//www') + '.google-analytics.com/ga.js'
    });
  </script>

Annotator/app/views/static_pages/home.html.erb
<% if signed_in? %>
  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section> 
      </section>
    </aside>
    <div class="span8">
      <h4><%= link_to image_tag("twitterBird.png", alt: "") %>Tweet to be annotated:</h4>
      <%= render 'shared/feed' %>
    </div>
  </div>  
<% else %>
  <div class="center hero-unit">
    <h1>Twitter annotation study</h1>

    <h2>
      A study into the challenges of detecting sarcasm on twitter.
    </h2>

    <p>
      Would you like to participate in the study and help out? <br>Follow the link to find out more about what the study entails and how you can take part. 
    </p>

    <%= link_to "Find out more", instructions_path, class: "btn btn-large btn-primary" %>
  </div>

  <b>PLEASE NOTE:</b>  For technical reasons, this study can only be conducted in FIREFOX, SAFARI or IE9+.  It won't work correctly in GOOGLE CHROME.  Please only particpate if you have access to one of these three browsers. (If you're interested in why, <%= link_to 'click here', why_not_chrome_path %>)

<%= link_to image_tag("me_speech.png", alt: "me") %>
</div>
<% end %>

Annotator/app/views/static_pages/why_not_chrome.html.erb
<p>For reasons best known to themselves, google chrome has chosen to not support <%= link_to 'emojis', 'http://en.wikipedia.org/wiki/Emoji' %>, Japanese style emoticons that are very popular on twitter.  These are often used to convey specific emotions and are therefore crucial in sentiment analysis.  
<p>Here are some example emojis:  </p>
🌀  💐 	💑 	💒 	💓 	💔 	💕 	💖 	💗 	💘 	
</p>
<p>If you are viewing this page on google chrome, you will simply see blank boxes.
</p>

Annotator/app/views/tweets/_tweets.html.erb
<li>
  <span class="content"><%= tweet.content %></span>
  <span class="timestamp">
    Retrieved <%= time_ago_in_words(tweet.created_at) %> ago.
  </span>
</li>

Annotator/app/views/tweets/edit.html.erb
subl <h1>Editing tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

Annotator/app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

Annotator/app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<%= link_to image_tag("consent.png", alt: "participant consent") %>
<p>Please read the following before signing up to participate in the study.  If you have any questions, please don't hesitate to contact me at albanies@tcd.ie</p>
<br>
<h3>
  Consent Form
</h3>
<br>
<h4>
Lead researcher
</h4> 
<br>
<p>
Samuel Albanie
</p>
<br>
<h4>
  Background to research
</h4>
<br>
<p>
  Please click <%= link_to "here", instructions_path %> if you wish to re-read the background to the study.
 </p>
 <br>
 <h4>
Procedure
</h4>
<br>
<p>
As a participant in the study, you will be provided with a randomly shuffled list of tweets, one tweet at a time. The task is simply to choose whether you believe the intended meaning of the tweet was positive, sarcastic or negative. All tweets themselves will be anonymous (user names will be removed).  Your contribution as a participant will be used anonymously.  You may abandon the study at any point should they wish to do so.  If for any reason you wish for your input to be deleted, please do not hesitate to email me at the email below and the data will be destroyed.
</p>
<br>
<h4>
Publication
</h4>
<br>
<p>
The research is being conducted as part of a masters dissertation, with the possibility of publication at the <%= link_to "WSDM 2014 conference", "http://www.wsdm-conference.org/2014/" %>.  
</p>
<br>
<h4>
DECLARATION: 
</h4>
<br>
<p>
  <ul>
  <li> I am 18 years or older and am competent to provide consent.</li>
  <br>
  <li>I understand that the tweets have not been filtered for content, and may therefore contain material of an adult nature.</li>
  <br>
<li> I have read, or had read to me, the page entitled 'information and instructions' providing information about this research and this consent form. I have had the opportunity to ask questions and all my questions have been answered to my satisfaction and understand the description of the research that is being provided to me. </li>
<br>
<li> I agree that my data is used for scientific purposes and I have no objection that my data is published in scientific publications in a way that does not reveal my identity. </li>
<br>
<li> I understand that if I make illicit activities known, these will be reported to appropriate authorities.</li>
<br>
<li> I freely and voluntarily agree to be part of this research study, though without prejudice to my legal and ethical rights. </li>
<br>
<li> I understand that I may refuse to answer any question and that I may withdraw at any time without penalty.</li>
<br>
<li>  I understand that my participation is fully anonymous and that no personal details about me will be recorded. </li>
<br>
<li> I understand that if I or anyone in my family has a history of epilepsy then I am proceeding at my own risk.</li>
<br>
<li> I have the option to receive a copy of this agreement.</li>
<br>
<h4>
Statement of investigator’s responsibility
</h4>
<br>
<p> I have explained the nature and purpose of this research study, the procedures to be undertaken and any risks that may be involved. I have offered to answer any questions and fully answered such questions. I believe that the participant understands my explanation and has freely given informed consent. 
</p>
<em> Samuel Albanie</em>
<br>
<br>
<h4>
Researcher contact details
</h4>
<br>
<p>
<em class="sentimentgreen">name:</em>Samuel Albanie
</p>
<p>
<em class="sentimentgreen">email:</em> albanies@tcd.ie
</p>
<br>
<h4>
Participant consent
</h4>
<br>
<p> By filling in the form below and clicking the 'I consent to participate' button, you are giving your consent to take part in the study, subject to the terms laid out above.
</p>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>
      
      <%= f.label :password, "password (minimum of six characters)" %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "password confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "I consent to participate", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>